services:
  nginx-proxy:
    build:
      context: ./nginx
      args:
        - HOSTNAME=example.com
    ports:
      - '80:80'
      - '443:443'
    command: [ nginx, '-g', 'daemon off;']
    networks:
      - nginx-network

# By default, Nexus 3 uses port 8081, so there's no need to declare this port.
# The port 5000 will be used for downloading Docker images via HTTP.

  nexus-repository:
    build:
      context: ./nexus3
      args:
        - TIMEZONE=Asia/Tashkent
    volumes:
      - /data/nexus-data:/nexus-data:rw
    networks:
      - nginx-network

volumes:
  nexus-data:

networks:
  nginx-network:

